"""
Final CARD artwork - used to override a character/weapon's card art via
/admin edit character or /admin edit weapon (the "image" option).
This does NOT affect the spawn image - that always comes from
soul.py / zanpaku.py (or /admin change character|weapon).
"""

CARD_IMAGES = {
    "Aaroniero Arruruerie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Aaroniero%20Arruruerie.jpg",
    "Ashishi Jizo (Shikai - Mayuri)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ashishi%20Jizo%20%28Shikai%29.jpg",
    "Askin Nakk Le Vaar": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Askin%20Nakk%20Le%20Vaar.webp",
    "BG9": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/BG9.jpg",
    "Bambietta Basterbine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Bambietta%20Basterbine.jpg",
    "Barragan Louisenbairn": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Barragan%20Louisenbair.jpg",
    "Bazz-B": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Bazz-B.jpg",
    "Benihime (Shikai - Urahara)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Benihime.jpg",
    "Byakuya Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Byakuya%20Kuchiki.jpg",
    "Candice Catnipp": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Candice%20Catnipp.jpg",
    "Cang Du": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Cang%20Du.jpg",
    "Chizuru Honsho": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Chizuru%20Honsho.jpg",
    "Chojiro Sasakibe": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Chojiro%20Sasakibe.webp",
    "Coyote Starrk": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Coyote%20Starrk.jpg",
    "Daiguren Hyorinmaru (Bankai - Toshiro)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Daiguren%20Hyorinmaru%20%28Bankai%29.jpg",
    "Don Kanonji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Don%20Kanonji.jpg",
    "Dondochakka Birtanne": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Dondochakka%20Birtanne.jpg",
    "Driscoll Berci": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Driscoll%20Berci.jpg",
    "Ganju Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ganju%20Shiba.jpg",
    "Gegetsuburi (Shikai - Omaeda)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Gegetsuburi.jpg",
    "Genryusai Shigekuni Yamamoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Genryusai%20Shigekuni%20Yamamoto.jpg",
    "Gerard Valkyrie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Gerard%20Valkyrie.jpg",
    "Gin Ichimaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Gin%20Ichimaru.jpg",
    "Ginrei Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ginrei%20Kuchiki.jpg",
    "Giriko Kutsuzawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/GirikoKutsuzawa.jpg",
    "Giselle Gewelle": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Giselle%20Gewelle.jpg",
    "Gonryomaru (Shikai - Sasakibe)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Gonryomaru%20%28Shikai%29.jpg",
    "Gremmy Thoumeaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Gremmy%20Thoumeaux.jpg",
    "Grimmjow Jaegerjaquez": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Grimmjow%20Jaegerjaquez.jpg",
    "Hachigen Ushoda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hachigen%20Ushoda.jpg",
    "Haguro Tonbo (Shikai - Iba)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Haguro%20Tonbo%20%28Shikai%29.jpg",
    "Haineko (Shikai - Rangiku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Haineko%20%28Shikai%29.jpg",
    "Hakka no Togame (Bankai - Rukia)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hakka%20no%20Togame%20%28Bankai%29.jpg",
    "Hanataro Yamada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hanataro%20Yamada.jpg",
    "Harribel": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Harribel.jpg",
    "Hiyori Sarugaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hiyori%20Sarugaki.jpg",
    "Hozukimaru (Shikai - Ikkaku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hozukimaru%20%28Shikai%29.jpg",
    "Hyorinmaru (Shikai - Toshiro)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Hyorinmaru%20%28Shikai%29.jpg",
    "Ichibei Hyosube": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ichibei%20Hyosube.jpg",
    "Ichigo Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/ichigo.jpg",
    "Ikkaku Madarame": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ikkaku%20Madarame.jpg",
    "Isane Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Isane%20Kotetsu.jpg",
    "Isshin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Isshin%20Kurosaki.jpg",
    "Izuru Kira": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Izuru%20Kira.jpg",
    "Jackie Tristan": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Jackie%20Tristan.jpg",
    "Jakuho Raikoben (Bankai - Soi Fon)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Jakuho%20Raikoben%20%28Bankai%29.jpg",
    "Jinta Hanakari": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Jinta%20Hanakari.jpg",
    "Jugram Haschwalth": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Jugram%20Haschwalth.jpg",
    "Jushiro Ukitake": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Jushiro%20Ukitake.jpg",
    "Kaien Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kaien%20Shiba.jpg",
    "Kamishini no Yari (Bankai - Gin)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kamishini%20no%20Yari%20%28Bankai%29.jpg",
    "Kannonbiraki Benihime Aratame (Bankai - Urahara)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kannonbiraki%20Benihime%20Aratame%20%28Bankai%29.jpg",
    "Karin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/KARIN.jpg",
    "Katen Kyokotsu (Shikai - Shunsui)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Katen%20Kyokotsu%20%28Shikai%29.jpg",
    "Katen Kyokotsu Karamatsu Shinju (Bankai - Shunsui)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Katen%20Kyokotsu%20Karamatsu%20Shinju.jpg",
    "Kazeshini (Shikai - Hisagi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kazeshini%20%28Shikai%29.jpg",
    "Kazui Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/kazui.jpg",
    "Keigo Asano": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Keigo%20Asano.jpg",
    "Kenpachi Zaraki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kenpachi%20Zaraki.jpg",
    "Kensei Muguruma": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kensei%20Muguruma.jpg",
    "Kinshara (Shikai - Rose)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kinshara%20%28Shikai%29.jpg",
    "Kinshara Butodan (Bankai - Rose)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kinshara%20Butodan%20%28Bankai%29.jpg",
    "Kirio Hikifune": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kirio%20Hikifune.jpg",
    "Kisuke Urahara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kisuke%20Urahara.jpg",
    "Kiyone Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kiyone%20Kotetsu.jpg",
    "Kokujo Tengen Myo'o (Bankai - Komamura)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kokujo%20Tengen%20Myo%27o%20%28Bankai%29.jpg",
    "Kon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/kon.jpg",
    "Konjiki Ashisogi Jizo (Bankai - Mayuri)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Konjiki%20Ashisogi%20Jizo%20%28Bankai%29.jpg",
    "Kugo Ginjo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kugo%20Ginjo.jpg",
    "Kukaku Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kukaku%20Shiba.jpg",
    "Kyoka Suigetsu (Shikai - Aizen)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Kyoka%20Suigetsu%20%28Shikai%29.jpg",
    "Lille Barro": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Lille%20Barro.jpg",
    "Liltotto Lamperd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Liltotto%20Lamperd.jpg",
    "Lilynette Gingerbuck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Lilynette%20Gingerbuck.jpg",
    "Lisa Yadomaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Lisa%20Yadomaru.jpg",
    "Love Aikawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Love%20Aikawa.jpg",
    "Loyd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Loyd%20Lloyd.jpg",
    "Luppi Antenor": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Luppi%20Antenor.jpg",
    "Makizo Aramaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Makizo%20Aramaki.jpg",
    "Marechiyo Omaeda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Marechiyo%20Omaeda.jpg",
    "Masaki Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Masaki%20Kurosaki.jpg",
    "Mashiro Kuna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Mashiro%20Kuna.jpg",
    "Mayuri Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Mayuri%20Kurotsuchi.jpg",
    "Meninas McAllon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Meninas%20McAllon.jpg",
    "Minazuki (Bankai - Unohana)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/minazuki%20bankai.jpg",
    "Mizuiro Kojima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Mizuiro%20Kojima.jpg",
    "Moe Shishigawara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Moe%20Shishigawara.jpg",
    "Momo Hinamori": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Momo%20Hinamori.jpg",
    "Nanana Najahkoop": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nanana%20Najahkoop.jpg",
    "Nanao Ise": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nanao%20Ise.jpg",
    "Nejibana (Shikai - Kaien)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nejibana%20%28Shikai%29.jpg",
    "Nelliel Tu Odelschwanck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nelliel%20Tu%20Odelschwanck.jpg",
    "Nemu Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nemu%20Kurotsuchi.jpg",
    "Nnoitra Gilga": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nnoitra%20Gilga.jpg",
    "Nozarashi (Bankai - Kenpachi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nozarashi%20%28Bankai%29.jpg",
    "Nozarashi (Shikai - Kenpachi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Nozarashi%20%28Shikai%29.jpg",
    "Oetsu Nimaiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Oetsu%20Nimaiya.jpg",
    "Orihime Inoue": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Orihime.jpg",
    "PePe Waccabrada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/PePe%20Waccabrada.jpg",
    "Pernida Parnkgjas": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Pernida%20Parnkgjas.jpg",
    "Pesche Guatiche": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Pesche%20Guatiche.jpg",
    "Quilge Opie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Quilge%20Opie.jpg",
    "Rangiku Matsumoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Rangiku%20Matsumoto.jpg",
    "Renji Abarai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Renji%20Abarai.jpg",
    "Retsu Unohana": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Retsu%20Unohana.jpg",
    "Riruka Dokugamine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Riruka%20Dokugamine.jpg",
    "Robert Accutrone": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Robert%20Accutrone.jpg",
    "Rose Otoribashi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Rose%20Otoribashi.jpg",
    "Royd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Royd%20Lloyd.jpg",
    "Rukia Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/rukia.jpg",
    "Ruri'iro Kujaku (Shikai - Yumichika)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ruri%27iro%20Kujaku%20%28Shikai%29.jpg",
    "Ryujin Jakka (Shikai - Yamamoto)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ryujin%20Jakka%20%28Shikai%29.jpg",
    "Ryumon Hozukimaru (Bankai - Ikkaku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ryumon%20Hozukimaru%20%28Bankai%29.jpg",
    "Sajin Komamura": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sajin%20Komamura.jpg",
    "Sakanade (Shikai - Shinji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sakanade%20%28Shikai%29.jpg",
    "Sakashima Yokoshima Happo Fusagari (Bankai - Shinji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sakashima%20Yokoshima%20Happo%20Fusagari%20%28Bankai%29.jpg",
    "Senbonzakura (Shikai - Byakuya)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Senbonzakura%20%28Shikai%29.jpg",
    "Senbonzakura Kageyoshi (Bankai - Byakuya)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Senbonzakura%20Kageyoshi%20%28Bankai%29.jpg",
    "Senjumaru Shutara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Senjumaru%20Shutara.jpg",
    "Sentaro Kotsubaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sentaro%20Kotsubaki.jpg",
    "Shaz Domino": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Shaz%20Domino.jpg",
    "Shinji Hirako": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Shinji%20Hirako.jpg",
    "Shinso (Shikai - Gin)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Shinso%20%28Shikai%29.jpg",
    "Shukuro Tsukishima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Shukuro%20Tsukishima.jpg",
    "Shunsui Kyoraku": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Shunsui%20Kyoraku.jpg",
    "Sode no Shirayuki (Shikai - Rukia)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sode%20no%20Shirayuki%20%28Shikai%29.jpg",
    "Sogyo no Kotowari (Shikai - Ukitake)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sogyo%20no%20Kotowari%20%28Shikai%29.jpg",
    "Soi Fon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Soi%20fon.jpg",
    "Soo Zabimaru (True Bankai - Renji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Soo%20Zabimaru%20%28True%20Bankai%29.jpg",
    "Sosuke Aizen": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Sosuke%20Aizen.jpg",
    "Suzumebachi (Shikai - Soi Fon)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Suzumebachi%20%28Shikai%29.jpg",
    "Szayelaporro Granz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Szayelaporro%20Granz.jpg",
    "Tachikaze (Shikai - Kensei)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tachikaze%20%28Shikai%29.jpg",
    "Tatsuki Arisawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tatsuki%20Arisawa.jpg",
    "Tekken Tachikaze (Bankai - Kensei)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tekken%20Tachikaze%20%28Bankai%29.jpg",
    "Tenjiro Kirinji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tenjiro%20Kirinji.jpg",
    "Tenken (Shikai - Komamura)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tenken%20%28Shikai%29.jpg",
    "Tensa Zangetsu (Bankai - Ichigo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tensa%20Zangetsu%20%28Bankai%29.jpg",
    "Tesra Lindocruz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tesra%20Lindocruz.jpg",
    "Tessai Tsukabishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tessai%20Tsukabishi.jpg",
    "Tetsuzaemon Iba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tetsuzaemon%20Iba.jpg",
    "Tobiume (Shikai - Momo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Tobiume%20%28Shikai%29.jpg",
    "Toshiro Hitsugaya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Toshiro%20Hitsugaya.jpg",
    "Ulquiorra Cifer": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ulquiorra%20Cifer.jpg",
    "Ururu Tsumugiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Ururu%20Tsumugiya.jpg",
    "Uryu Ishida": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/uryu.jpg",
    "Wabisuke (Shikai - Kira)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Wabisuke%20%28Shikai%29.jpg",
    "Wonderweiss Margela": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Wonderweiss%20Margela.jpg",
    "Yachiru Kusajishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yachiru%20Kusajishi.jpg",
    "Yammy Llargo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yammy%20Llargo.jpg",
    "Yasutora Sado (Chad)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/chad.jpg",
    "Yhwach": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yhwach.jpg",
    "Yoruichi Shihoin": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yoruichi%20Shihoin.jpg",
    "Yukio Hans Vorarlberna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yukio%20Hans%20Vorarlberna.jpg",
    "Yumichika Ayasegawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yumichika%20Ayasegawa.jpg",
    "Yuzu Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Yuzu.jpg",
    "Zabimaru (Shikai - Renji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Zabimaru%20%28Shikai%29.jpg",
    "Zangetsu (Shikai - Ichigo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Zangetsu%20%28Shikai%29.jpg",
    "Zanka no Tachi (Bankai - Yamamoto)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Zanka%20no%20Tachi%20%28Bankai%29.jpg",
    "Zommari Rureaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/cards/Zommari%20Rureaux.jpg",
}