"""
Character artwork - GitHub-hosted images used by /admin character add.
Key MUST exactly match the name used in the bot (character list from card_url.txt).
"""

CHARACTER_IMAGES = {
    "Aaroniero Arruruerie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Aaroniero%20Arruruerie.png",
    "Abirama Redder": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Abirama%20Redder.png",
    "Ashisogi Jizo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ashisogi%20Jizo.png",
    "Askin Nakk Le Vaar": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Askin%20Nakk%20Le%20Vaar.png",
    "Aura Michibane": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Aura%20Michibane.png",
    "Bambietta Basterbine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Bambietta%20Basterbine.png",
    "Ban": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ban.png",
    "Barragan Louisenbairn": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Barragan%20Louisenbairn.png",
    "Bau": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Bau.png",
    "Bazz-B": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Bazz-B.png",
    "Benin": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Benin.png",
    "BG9": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/BG9.png",
    "Byakuya Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Byakuya%20Kuchiki.png",
    "Candice Catnipp": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Candice%20Catnipp.png",
    "Cang Du": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Cang%20Du.png",
    "Charlotte Chuhlhourne": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Charlotte%20Chuhlhourne.png",
    "Chizuru Honsho": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Chizuru%20Honsho.png",
    "Choe Neng Poww": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Choe%20Neng%20Poww.png",
    "Chojiro Sasakibe": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Chojiro%20Sasakibe.png",
    "Cirucci Sanderwicci": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Cirucci%20Sanderwicci.png",
    "Coyote Starrk": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Coyote%20Starrk.png",
    "Cyan Sun-Sun": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Cyan%20Sun-Sun.png",
    "Don Kanonji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Don%20Kanonji.png",
    "Dondochakka Birstanne": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Dondochakka%20Birtanne.png",
    "Dordoni Alessandro Del Socaccio": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Dordoni%20Alessandro%20Del%20Socaccio.png",
    "Driscoll Berci": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Driscoll%20Berci.png",
    "Edrad Liones": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Edrad%20Liones.png",
    "Emilou Apacci": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/emilou%20apacci.png",
    "Enryu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Enryu.png",
    "Findorr Calius": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Findorr%20Calius.png",
    "Franceska Mila Rose": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Franceska%20Mila%20Rose.png",
    "Ganju Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ganju%20Shiba.png",
    "Ganryu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ganryu.png",
    "Gantenbainne Mosqueda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gantenbainne%20Mosqueda.png",
    "Garogai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Garogai.png",
    "Gegetsuburi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gegetsuburi.png",
    "Genga": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/genga.png",
    "Genryusai Shigekuni Yamamoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Genryusai%20Shigekuni%20Yamamoto.png",
    "Gerard Valkyrie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gerard%20Valkyrie.png",
    "Gesell": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gesell.png",
    "Ggio Vega": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ggio%20Vega.png",
    "Gin Ichimaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gin%20Ichimaru.png",
    "Ginrei Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ginrei%20Kuchiki.png",
    "Giriko Kutsuzawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Giriko%20Kutsuzawa.png",
    "Giselle Gewelle": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Giselle%20Gewelle.png",
    "Go Koga": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Go%20Koga.png",
    "Gonryomaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gonryomaru.png",
    "Grand Fisher": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Grand%20Fisher.png",
    "Gremmy Thoumeaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gremmy%20Thoumeaux.png",
    "Grimmjow Jaegerjaquez": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/grimmjow.png",
    "Gunjo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/gunjo.png",
    "Gyakuaku Kumoi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Gyakuaku%20Kumoi.png",
    "Hachigen Ushoda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hachigen%20Ushoda.png",
    "Haineko": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Haineko.png",
    "Hanataro Yamada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hanataro%20Yamada.png",
    "Hanza Nukui": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hanza%20Nukui.png",
    "Tier Harribel": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tier%20Harribel.png",
    "Hikone Ubuginu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hikone%20Ubuginu.png",
    "Hisagomaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hisagomaru.png",
    "Hiyori Sarugaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hiyori%20Sarugaki.png",
    "Ho": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ho.png",
    "Homura": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Homura.png",
    "Hozukimaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hozukimaru.png",
    "Ichibei Hyosube": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ichibei%20Hyosube.png",
    "Ichigo Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ichigo%20Kurosaki.png",
    "Ikkaku Madarame": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ikkaku%20Madarame.png",
    "Ikumi Unagiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ikumi%20Unagiya.png",
    "Isane Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Isane%20Kotetsu.png",
    "Isshin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Isshin%20Kurosaki.png",
    "Izuru Kira": "https://github.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Izuru%20Kira.png",
    "Jackie Tristan": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jackie%20Tristan.png",
    "Jai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jai.png",
    "Jin Kariya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jin%20Kariya.png",
    "Jinnai Douko": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jinnai%20Douko.png",
    "Jinta Hanakari": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jinta%20Hanakari.png",
    "Jugram Haschwalth": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Jugram%20Haschwalth.png",
    "Jushiro Ukitake": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ukitake.png",
    "Kageroza Inaba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kageroza%20Inaba.png",
    "Kaien Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kaien%20Shiba.png",
    "Kaname Tosen": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kaname%20Tosen.png",
    "Kaoru Unagiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kaoru%20Unagiya.png",
    "Karin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Karin%20Kurosaki.png",
    "Kazeshini": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kazeshini.png",
    "Kazui Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kazui%20Kurosaki.png",
    "Keigo Asano": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Keigo%20Asano.png",
    "Kenpachi Kiganjo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kenpachi%20Kiganjo.png",
    "Kenpachi Zaraki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kenpachi%20Zaraki.png",
    "Kenryu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kenryu.png",
    "Kensei Muguruma": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kensei%20Muguruma.png",
    "Kirikaze": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kirikaze.png",
    "Kirio Hikifune": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Hikifune.png",
    "Kisuke Urahara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kisuke%20Urahara.png",
    "Kiyone Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kiyone%20Kotetsu.png",
    "Kokuto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kokuto.png",
    "Kon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/kon.png",
    "Kugo Ginjo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kugo%20Ginjo.png",
    "Kukaku Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kukaku%20Shiba.png",
    "Kurudo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kurudo.png",
    "Kuruyashiki Kenpachi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Kuruyashiki%20Kenpachi.png",
    "Lille Barro": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Lille%20Barro.png",
    "Liltotto Lamperd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Liltotto%20Lamperd.png",
    "Lilynette Gingerbuck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Lilynette%20Gingerbuck.png",
    "Lisa Yadomaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Lisa%20Yadomaru.png",
    "Love Aikawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Love%20Aikawa.png",
    "Loyd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Loyd%20Lloyd.png",
    "Luppi Antenor": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Luppi%20Antenor.png",
    "Lurichiyo Kasumiōji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Rurichiyo%20Kasumioji.png",
    "Mabashi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mabashi.png",
    "Maki Ichinose": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Maki%20Ichinose.png",
    "Makizo Aramaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Makizo%20Aramaki.png",
    "Makoto Kibune": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Makoto%20Kibune.png",
    "Marechiyo Omaeda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Marechiyo%20Omaeda.png",
    "Masaki Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Masaki%20Kurosaki.png",
    "Mashiro Kuna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mashiro%20Kuna.png",
    "Mask De Masculine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mask%20De%20Masculine.png",
    "Mayuri Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mayuri%20Kurotsuchi.png",
    "Meninas McAllon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Meninas%20McAllon.png",
    "Mizuiro Kojima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mizuiro%20Kojima.png",
    "Moe Shishigawara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Moe%20Shishigawara.png",
    "Momo Hinamori": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Momo%20Hinamori.png",
    "Mue": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Mue.png",
    "Muramasa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Muramasa.png",
    "NaNaNa Najahkoop": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nanana%20Najahkoop.png",
    "Nanao Ise": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nanao%20Ise.png",
    "Narunosuke": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Narunosuke.png",
    "Nelliel Tu Odelschwanck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nelliel%20Tu%20Odelschwanck.png",
    "Nemu Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nemu%20Kurotsuchi.png",
    "Nianzol Weizol": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nianzol%20Weizol.png",
    "Nirgge Parduoc": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nirgge%20Parduoc.png",
    "Nnoitra Gilga": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nnoitra%20Gilga.png",
    "Noba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Noba.png",
    "Nozomi Kujo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Nozomi%20Kujo.png",
    "Oetsu Nimaiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Oetsu%20Nimaiya.png",
    "Ohana Katen": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ohana.png",
    "Oko Yushima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Oko%20Yushima.png",
    "Okyo Kyokotsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Okyo.png",
    "Orihime Inoue": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Orihime%20Inoue.png",
    "Ouko Yushima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ouko%20Yushima.png",
    "PePe Waccabrada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/PePe%20Waccabrada.png",
    "Pernida Parnkgjas": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Pernida%20Parnkgjas.png",
    "Pesche Guatiche": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Pesche%20Guatiche.png",
    "Quilge Opie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Quilge%20Opie.png",
    "Rangiku Matsumoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Rangiku%20Matsumoto.png",
    "Renji Abarai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Renji.png",
    "Retsu Unohana": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Retsu%20Unohana.png",
    "Ririn": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ririn.png",
    "Riruka Dokugamine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Riruka%20Dokugamine.png",
    "Riyan": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Riyan.png",
    "Robert Accutrone": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Robert%20Accutrone.png",
    "Roka Paramia": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Roka%20Paramia.png",
    "Rose Otoribashi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Rose%20Otoribashi.png",
    "Royd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Royd%20Lloyd.png",
    "Rudbornn Chelute": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Rudbornn%20Chelute.png",
    "Rukia Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Rukia%20Kuchiki.png",
    "Ruri'iro Kujaku": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ruri%27iro%20Kujaku.png",
    "Ryu Kuzu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ryu%20Kuzu.png",
    "Ryuken Ishida": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ryuken%20Ishida.png",
    "Sajin Komamura": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sajin%20Komamura.png",
    "Sakanade": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sakanade.png",
    "Sawatari": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sawatari.png",
    "Senjumaru Shutara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Senjumaru%20Shutara.png",
    "Senna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Senna.png",
    "Sentaro Kotsubaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sentaro%20Kotsubaki.png",
    "Shawlong Koufang": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shawlong%20Koufang.png",
    "Shaz Domino": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shaz%20Domino.png",
    "Shinji Hirako": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shinji.png",
    "Shintaro": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shintaro.png",
    "Shizuku": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shizuku.png",
    "Shuhei Hisagi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shuhei%20Hisagi.png",
    "Shukuro Tsukishima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shukuro%20Tsukishima.png",
    "Shunsui Kyoraku": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shunsui%20Kyoraku.png",
    "Shuren": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shuren.png",
    "Shusuke Amagai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Shusuke%20Amagai.png",
    "Sogyo no Kotowari": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sogyo%20no%20Kotowari.png",
    "Soi Fon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Soi%20Fon.png",
    "Sojiro Kusaka": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sojiro%20Kusaka.png",
    "Sojun Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sojun%20Kuchiki.png",
    "Sosuke Aizen": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Sosuke%20Aizen.png",
    "Soul King": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Soul%20King.png",
    "Suzumebachi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Suzumebachi.png",
    "Szayelaporro Granz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Szayelaporro%20Granz.png",
    "Taikun": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Taikun.png",
    "Tatsuki Arisawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tatsuki%20Arisawa.png",
    "Tenjiro Kirinji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tenjiro%20Kirinji.png",
    "Tenken": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tenken.png",
    "Tesra Lindocruz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tesra%20Lindocruz.png",
    "Tessai Tsukabishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tessai%20Tsukabishi.png",
    "Tetsuzaemon Iba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tetsuzaemon%20Iba.png",
    "Tobiume": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tobiume.png",
    "Tokinada Tsunayashiro": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Tokinada%20Tsunayashiro.png",
    "Toshiro Hitsugaya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Toshiro%20Hitsugaya.png",
    "Ugaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ugaki.png",
    "Ulquiorra Cifer": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ulquiorra%20Cifer.png",
    "Ururu Tsumugiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Ururu%20Tsumugiya.png",
    "Uryu Ishida": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Uryu%20Ishida.png",
    "Wabisuke": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Wabisuke.png",
    "Wonderweiss Margela": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Wonderweiss%20Margela.png",
    "Yachiru Kusajishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yachiru.png",
    "Yammy Llargo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yammy%20Llargo.png",
    "Yang": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yang.png",
    "Yasutora Sado": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yasutora%20Sado.png",
    "Yhwach": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yhwach.png",
    "Yin": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yin.png",
    "Yoruichi Shihoin": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yoruichi%20Shihoin.png",
    "Yoshi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yoshi.png",
    "Yoshino Soma": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yoshino%20Soma.png",
    "Yukio Hans Vorarlberna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yukio%20Hans%20Vorarlberna.png",
    "Yumichika Ayasegawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yumichika%20Ayasegawa.png",
    "Yuzu Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yuzu.png",
    "Yylfordt Granz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Yylfordt%20Granz.png",
    "Zabimaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Zabimaru.png",
    "Zommari Rureaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/Zommari%20Rureaux.png",
    "Äs Nödt": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/new%20soul%20images/New%20Character%20Images/%C3%84s%20N%C3%B6dt.png",
}