"""
Character artwork - GitHub-hosted images used by /admin character add.
Key MUST exactly match the name used in the bot (character list from card_url.txt).
"""

CHARACTER_IMAGES = {
    "Aaroniero Arruruerie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Aaroniero%20Arruruerie.png",
    "Askin Nakk Le Vaar": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Askin%20Nakk%20Le%20Vaar.png",
    "BG9": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/BG9.png",
    "Bambietta Basterbine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Bambietta%20Basterbine.png",
    "Barragan Louisenbairn": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Barragan%20Louisenbair.png",
    "Bazz-B": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Bazz-B.png",
    "Byakuya Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Byakuya%20Kuchiki.png",
    "Candice Catnipp": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Candice%20Catnipp.png",
    "Cang Du": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Cang%20Du.png",
    "Chizuru Honsho": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Chizuru%20Honsho.png",
    "Chojiro Sasakibe": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Chojiro%20Sasakibe.png",
    "Coyote Starrk": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Coyote%20Starrk.png",
    "Don Kanonji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Don%20Kanonji.png",
    "Dondochakka Birtanne": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Dondochakka%20Birtanne.png",
    "Driscoll Berci": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Driscoll%20Berci.png",
    "Ganju Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ganju%20Shiba.png",
    "Genryusai Shigekuni Yamamoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Genryusai%20Shigekuni%20Yamamoto.png",
    "Gerard Valkyrie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Gerard%20Valkyrie.png",
    "Gin Ichimaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Gin%20Ichimaru.png",
    "Ginrei Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ginrei%20Kuchiki.png",
    "Giriko Kutsuzawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/GirikoKutsuzawa.png",
    "Giselle Gewelle": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Giselle%20Gewelle.png",
    "Gremmy Thoumeaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Gremmy%20Thoumeaux.png",
    "Grimmjow Jaegerjaquez": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Grimmjow%20Jaegerjaquez.png",
    "Hachigen Ushoda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Hachigen%20Ushoda.png",
    "Hanataro Yamada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Hanataro%20Yamada.webp",
    "Harribel": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Harribel.png",
    "Hiyori Sarugaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Hiyori%20Sarugaki.png",
    "Ichibei Hyosube": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ichibei%20Hyosube.png",
    "Ichigo Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/ichigo.png",
    "Ikkaku Madarame": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ikkaku%20Madarame.png",
    "Isane Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Isane%20Kotetsu.png",
    "Isshin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Isshin%20Kurosaki.png",
    "Izuru Kira": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Izuru%20Kira.png",
    "Jackie Tristan": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Jackie%20Tristan.png",
    "Jinta Hanakari": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Jinta%20Hanakari.png",
    "Jugram Haschwalth": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Jugram%20Haschwalth.png",
    "Jushiro Ukitake": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Jushiro%20Ukitake.png",
    "Kaien Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kaien%20Shiba.png",
    "Karin Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/KARIN.png",
    "Kazui Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/kazui.png",
    "Keigo Asano": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Keigo%20Asano.png",
    "Kenpachi Zaraki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kenpachi%20Zaraki.png",
    "Kensei Muguruma": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kensei%20Muguruma.png",
    "Kirio Hikifune": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kirio%20Hikifune.png",
    "Kisuke Urahara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kisuke%20Urahara.png",
    "Kiyone Kotetsu": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kiyone%20Kotetsu.png",
    "Kon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/kon.png",
    "Kugo Ginjo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kugo%20Ginjo.png",
    "Kukaku Shiba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Kukaku%20Shiba.png",
    "Lille Barro": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Lille%20Barro.png",
    "Liltotto Lamperd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Liltotto%20Lamperd.png",
    "Lilynette Gingerbuck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Lilynette%20Gingerbuck.png",
    "Lisa Yadomaru": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Lisa%20Yadomaru.png",
    "Love Aikawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Love%20Aikawa.png",
    "Loyd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Loyd%20Lloyd.png",
    "Luppi Antenor": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Luppi%20Antenor.png",
    "Makizo Aramaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Makizo%20Aramaki.png",
    "Marechiyo Omaeda": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Marechiyo%20Omaeda.png",
    "Masaki Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Masaki%20Kurosaki.png",
    "Mashiro Kuna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Mashiro%20Kuna.png",
    "Mayuri Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Mayuri%20Kurotsuchi.png",
    "Meninas McAllon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Meninas%20McAllon.png",
    "Mizuiro Kojima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Mizuiro%20Kojima.png",
    "Moe Shishigawara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Moe%20Shishigawara.png",
    "Momo Hinamori": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Momo%20Hinamori.png",
    "Nanana Najahkoop": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Nanana%20Najahkoop.png",
    "Nanao Ise": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Nanao%20Ise.png",
    "Nelliel Tu Odelschwanck": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Nelliel%20Tu%20Odelschwanck.png",
    "Nemu Kurotsuchi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Nemu%20Kurotsuchi.png",
    "Nnoitra Gilga": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Nnoitra%20Gilga.png",
    "Oetsu Nimaiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Oetsu%20Nimaiya.png",
    "Orihime Inoue": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Orihime.png",
    "PePe Waccabrada": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/PePe%20Waccabrada.png",
    "Pernida Parnkgjas": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Pernida%20Parnkgjas.png",
    "Pesche Guatiche": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Pesche%20Guatiche.png",
    "Quilge Opie": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Quilge%20Opie.png",
    "Rangiku Matsumoto": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Rangiku%20Matsumoto.png",
    "Renji Abarai": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Renji%20Abarai.png",
    "Retsu Unohana": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Retsu%20Unohana.png",
    "Riruka Dokugamine": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Riruka%20Dokugamine.png",
    "Robert Accutrone": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Robert%20Accutrone.png",
    "Rose Otoribashi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Rose%20Otoribashi.png",
    "Royd Lloyd": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Royd%20Lloyd.png",
    "Rukia Kuchiki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/rukia.png",
    "Sajin Komamura": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Sajin%20Komamura.png",
    "Senjumaru Shutara": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Senjumaru%20Shutara.png",
    "Sentaro Kotsubaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Sentaro%20Kotsubaki.png",
    "Shaz Domino": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Shaz%20Domino.png",
    "Shinji Hirako": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Shinji%20Hirako.png",
    "Shukuro Tsukishima": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Shukuro%20Tsukishima.png",
    "Shunsui Kyoraku": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Shunsui%20Kyoraku.png",
    "Soi Fon": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Soi%20Fon.png",
    "Sosuke Aizen": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Sosuke%20Aizen.png",
    "Szayelaporro Granz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Szayelaporro%20Granz.png",
    "Tatsuki Arisawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Tatsuki%20Arisawa.png",
    "Tenjiro Kirinji": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Tenjiro%20Kirinji.png",
    "Tesra Lindocruz": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Tesra%20Lindocruz.png",
    "Tessai Tsukabishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Tessai%20Tsukabishi.png",
    "Tetsuzaemon Iba": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Tetsuzaemon%20Iba.png",
    "Toshiro Hitsugaya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Toshiro%20Hitsugaya.png",
    "Ulquiorra Cifer": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ulquiorra%20Cifer.png",
    "Ururu Tsumugiya": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Ururu%20Tsumugiya.png",
    "Uryu Ishida": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/uryu.png",
    "Wonderweiss Margela": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Wonderweiss%20Margela.png",
    "Yachiru Kusajishi": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yachiru%20Kusajishi.png",
    "Yammy Llargo": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yammy%20Llargo.png",
    "Yasutora Sado (Chad)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/chad.png",
    "Yhwach": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yhwach.png",
    "Yoruichi Shihoin": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yoruichi%20Shihoin.png",
    "Yukio Hans Vorarlberna": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yukio%20Hans%20Vorarlberna.png",
    "Yumichika Ayasegawa": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yumichika%20Ayasegawa.png",
    "Yuzu Kurosaki": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Yuzu.png",
    "Zommari Rureaux": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/character%20image/Zommari%20Rureaux.png",
}
