"""
Zanpakuto/weapon artwork - GitHub-hosted images used by /admin weapon add.
"""

WEAPON_IMAGES = {
    "Ashishi Jizo (Shikai - Mayuri)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Ashishi%20Jizo%20%28Shikai%29.png",
    "Benihime (Shikai - Urahara)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Benihime.png",
    "Daiguren Hyorinmaru (Bankai - Toshiro)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Daiguren%20Hyorinmaru%20%28Bankai%29.png",
    "Gegetsuburi (Shikai - Omaeda)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Gegetsuburi.png",
    "Gonryomaru (Shikai - Sasakibe)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Gonryomaru%20%28Shikai%29.png",
    "Haguro Tonbo (Shikai - Iba)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Haguro%20Tonbo%20%28Shikai%29.png",
    "Haineko (Shikai - Rangiku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Haineko%20%28Shikai%29.png",
    "Hakka no Togame (Bankai - Rukia)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Hakka%20no%20Togame%20%28Bankai%29.png",
    "Hozukimaru (Shikai - Ikkaku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Hozukimaru%20%28Shikai%29.png",
    "Hyorinmaru (Shikai - Toshiro)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Hyorinmaru%20%28Shikai%29.png",
    "Jakuho Raikoben (Bankai - Soi Fon)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Jakuho%20Raikoben%20%28Bankai%29.png",
    "Kamishini no Yari (Bankai - Gin)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kamishini%20no%20Yari%20%28Bankai%29.png",
    "Kannonbiraki Benihime Aratame (Bankai - Urahara)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kannonbiraki%20Benihime%20Aratame%20%28Bankai%29.png",
    "Katen Kyokotsu (Shikai - Shunsui)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Katen%20Kyokotsu%20%28Shikai%29.png",
    "Katen Kyokotsu Karamatsu Shinju (Bankai - Shunsui)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Katen%20Kyokotsu%20Karamatsu%20Shinju.png",
    "Kazeshini (Shikai - Hisagi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kazeshini%20%28Shikai%29.png",
    "Kinshara (Shikai - Rose)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kinshara%20%28Shikai%29.png",
    "Kinshara Butodan (Bankai - Rose)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kinshara%20Butodan%20%28Bankai%29.png",
    "Kokujo Tengen Myo'o (Bankai - Komamura)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kokujo%20Tengen%20Myo%27o%20%28Bankai%29.png",
    "Konjiki Ashisogi Jizo (Bankai - Mayuri)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Konjiki%20Ashisogi%20Jizo%20%28Bankai%29.png",
    "Kyoka Suigetsu (Shikai - Aizen)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Kyoka%20Suigetsu%20%28Shikai%29.png",
    "Minazuki (Bankai - Unohana)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Minazuki%20%28Bankai%29.png",
    "Nejibana (Shikai - Kaien)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Nejibana%20%28Shikai%29.png",
    "Nozarashi (Bankai - Kenpachi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Nozarashi%20%28Bankai%29.png",
    "Nozarashi (Shikai - Kenpachi)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Nozarashi%20%28Shikai%29.png",
    "Ruri'iro Kujaku (Shikai - Yumichika)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Ruri%27iro%20Kujaku%20%28Shikai%29.png",
    "Ryujin Jakka (Shikai - Yamamoto)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Ryujin%20Jakka%20%28Shikai%29.png",
    "Ryumon Hozukimaru (Bankai - Ikkaku)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Ryumon%20Hozukimaru%20%28Bankai%29.png",
    "Sakanade (Shikai - Shinji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Sakanade%20%28Shikai%29.png",
    "Sakashima Yokoshima Happo Fusagari (Bankai - Shinji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Sakashima%20Yokoshima%20Happo%20Fusagari%20%28Bankai%29.png",
    "Senbonzakura (Shikai - Byakuya)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Senbonzakura%20%28Shikai%29.png",
    "Senbonzakura Kageyoshi (Bankai - Byakuya)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Senbonzakura%20Kageyoshi%20%28Bankai%29.png",
    "Shinso (Shikai - Gin)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Shinso%20%28Shikai%29.png",
    "Sode no Shirayuki (Shikai - Rukia)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Sode%20no%20Shirayuki%20%28Shikai%29.png",
    "Sogyo no Kotowari (Shikai - Ukitake)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Sogyo%20no%20Kotowari%20%28Shikai%29.png",
    "Soo Zabimaru (True Bankai - Renji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Soo%20Zabimaru%20%28True%20Bankai%29.png",
    "Suzumebachi (Shikai - Soi Fon)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Suzumebachi%20%28Shikai%29.png",
    "Tachikaze (Shikai - Kensei)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Tachikaze%20%28Shikai%29.png",
    "Tekken Tachikaze (Bankai - Kensei)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Tekken%20Tachikaze%20%28Bankai%29.png",
    "Tenken (Shikai - Komamura)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Tenken%20%28Shikai%29.png",
    "Tensa Zangetsu (Bankai - Ichigo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Tensa%20Zangetsu%20%28Bankai%29.png",
    "Tobiume (Shikai - Momo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Tobiume%20%28Shikai%29.png",
    "Wabisuke (Shikai - Kira)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Wabisuke%20%28Shikai%29.png",
    "Zabimaru (Shikai - Renji)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Zabimaru%20%28Shikai%29.png",
    "Zangetsu (Shikai - Ichigo)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Zangetsu%20%28Shikai%29.png",
    "Zanka no Tachi (Bankai - Yamamoto)": "https://raw.githubusercontent.com/craftmasters26/bleachdex/main/BleachDex%20Discord%20Bot/images/zanputo%20image/Zanka%20no%20Tachi%20%28Bankai%29.png",
}
