"""
Flavor text shown above a spawn, in the spirit of Bleach. These are
original lines written in the tone of the series, not verbatim quotes
pulled from the show/manga - keeps things flavorful without needing to
reproduce copyrighted dialogue.
"""

import random

SPAWN_QUOTES = [
    "If you don't catch me, somebody else will.",
    "A blade left undrawn cuts no one — draw quickly.",
    "Even the weakest soul can seize a chance like this.",
    "This reiatsu won't linger in the world of the living for long.",
    "Hesitation is a soul reaper's worst enemy. Move.",
    "The Soul Society doesn't wait for the slow.",
    "Somewhere, a hollow is laughing at your indecision.",
    "Bankai isn't the only thing that takes a split second to lose.",
    "Every soul reaper in Karakura Town just felt this appear.",
    "Speed isn't everything — but right now, it's the only thing.",
    "A presence flickers at the edge of your senses. Don't blink.",
    "Something just stepped out of the Garganta. Move.",
    "The air's gone heavy. That's your cue.",
    "This one won't sit still for long.",
    "Reiatsu spike detected. First one to it wins.",
    "Even the Senkaimon closes eventually. This won't last.",
    "A soul just surfaced. Claim it before it fades.",
    "Karakura's gotten noisy again. Something's here.",
    "That's not a Hollow — that's a chance. Take it.",
    "Flash step now, ask questions later.",
    "The Dangai spits out opportunities like this. Rarely twice.",
    "One breath of hesitation and it's gone. Breathe later.",
    "A new signature just bled into the air. Read it fast.",
    "The gates opened. Whatever walked through won't wait.",
    "Something's standing in the open. Say its name.",
    "Reiatsu doesn't repeat itself. This is your only look.",
    "A blade just cleared its sheath. Whose is it?",
    "The world just shifted. Catch it before it settles.",
    "Every second you stare is a second someone else moves.",
    "A soul steps into the light. Name it and it's yours.",
    "This pressure isn't ambient — it's an invitation.",
    "Whatever just arrived, it knows you sensed it.",
    "The air's cracked open. Something's on the other side.",
    "Don't study it. Recognize it. Now.",
    "A signature flares once and fades. That's your window.",
    "One chance. One name. One second. Go.",
    "Something just announced itself to anyone listening.",
    "Reiatsu this sharp belongs to someone specific. Who?",
    "Karakura doesn't get quiet for long. It just got loud.",
    "A presence just crossed into your range. Lock on.",
    "The fight starts the moment you see it. It's already started.",
    "First one to speak the name takes it. Everyone else watches.",
]


def random_spawn_quote() -> str:
    return random.choice(SPAWN_QUOTES)


# Shown (publicly, mentioning the guesser) when someone's guess is wrong
# or when someone else already caught the spawn first.
# Bleach-flavored ribbing only - never generic insults.
ROAST_QUOTES = [
    "Even Kon could've guessed that one, {user}.",
    "That guess had less bite than Zangetsu's blunt side, {user}.",
    "Yamamoto retired faster than your brain just worked, {user}.",
    "Even a Hollow with half a mask could've named that, {user}.",
    "Chad talks more than that guess made sense, {user}.",
    "Your reiatsu for guessing is Academy Year One at best, {user}.",
    "Ganju could rebuild a whole railway faster than you got that right, {user}.",
    "Even Rukia's terrible drawings are more recognizable than that guess, {user}.",
    "That was weaker than Ichigo's excuses for skipping class, {user}.",
    "Nice try, but even Keigo saw that one coming - and missed too, {user}.",
    "This wasn't part of Aizen's plan, {user}.",
    "That guess was so far off it landed in Hueco Mundo, {user}.",
    "{user}, even the Soul King's left arm could've done better.",
    "That answer had all the aim of a blind Quincy, {user}.",
    "You guessed like you were swinging Zangetsu by the cloth, {user}.",
    "Your inner Hollow would be embarrassed, {user}.",
    "{user}, Yachiru could've picked better with her eyes closed.",
    "That was less accurate than a Bount's moral compass, {user}.",
    "You brought a guess like that to a captain's fight, {user}?",
    "Even the Mod Souls are cringing, {user}.",
    "That attempt had the precision of a Hollow's table manners, {user}.",
    "{user}, Kenpachi fights with more strategy than that guess.",
    "Mayuri's rejected experiments guess better than that, {user}.",
    "That guess dissolved faster than a low-level Hollow in sunlight, {user}.",
    "You swung blind and hit the wrong dimension, {user}.",
    "{user}, that guess had the conviction of a Shinigami filing paperwork.",
    "You guessed like Hanataro fights — earnestly, and badly, {user}.",
    "Even the gate guards would've turned that answer away, {user}.",
    "{user}, that was the guess equivalent of tripping into the Dangai.",
    "Your answer had less resolve than a Hollow's promise, {user}.",
    "{user}, Ukitake coughed up better answers than that.",
    "That guess needed a captain's approval. It got none, {user}.",
    "{user}, even Nemu processes faster than that.",
    "You answered like you'd never read a single chapter, {user}.",
    "That was the kind of guess that gets a squad demoted, {user}.",
    "{user}, Tessai's forbidden Kido is less of a disaster than that.",
    "Your guess had the tactical genius of running at Kenpachi head-on, {user}.",
    "{user}, even the Bount arc made more sense than that answer.",
    "That guess would've failed Yamamoto's entrance exam, {user}.",
    "{user}, you named that like you were guessing someone's Zanpakuto spirit. Wrong.",
    "Even the cleaner in the Dangai is more decisive, {user}.",
    "{user}, that answer had all the sharpness of a dull Asauchi.",
    "You guessed like Aizen told you the answer and lied, {user}.",
    "That was a Vice-Captain's guess at best, {user}.",
    "{user}, the Kido Corps rejects answers like that for being too unstable.",
    "You just named the wrong person in front of the entire Gotei 13, {user}.",
    "Even Orihime's cooking is more accurate than that, {user}.",
    "{user}, that guess had the lifespan of a candle in a storm.",
    "Your answer died faster than a filler villain, {user}.",
    "{user}, even Soi Fon's two-hit kill needed more than that to land.",
    "That guess was so wrong the Hogyoku couldn't fix it, {user}.",
    "Too slow, {user} — that one's already claimed.",
    "{user} arrived like a Shinigami to a battle that ended an hour ago.",
    "Someone else flash-stepped first, {user}.",
    "That soul's already got an owner, {user}. Next time, move faster.",
    "{user} showed up after the credits rolled.",
    "You hesitated, {user}. Somebody else didn't.",
    "The Senkaimon already closed on that one, {user}.",
    "{user}, you're about as timely as the Vizards revealing themselves.",
    "That one's gone, {user} — bled right through your fingers.",
    "Late to the fight again, {user}. The blade's already sheathed.",
    "By the time you moved, {user}, the fight was already a memory.",
    "That window shut before you even reached for it, {user}.",
    "You watched. Someone else acted. That's the whole story, {user}.",
    "{user}, even Hanataro would've gotten there before you.",
    "The dust settled, {user} — and you weren't in it.",
    "{user}, the kill was already confirmed before you drew breath.",
    "Someone else called it. You just witnessed history, {user}.",
    "{user}, you moved like the fight was optional. It wasn't.",
    "That name's been spoken, {user}. You're echoing, not answering.",
    "{user}, you got there in time to watch. That's it.",
    "The window closed, {user}. You were still deciding.",
    "By the time your guess landed, the fight had a winner, {user}.",
    "{user}, you arrived like a captain to a lieutenant's fight — after it ended.",
    "That one's sealed, {user}. Someone got the Bankai first.",
    "You blinked, {user}. That's the whole reason you lost it.",
    "{user}, even the gate guards would've moved faster than that.",
    "Someone's already wearing that victory, {user}.",
    "The blade fell before you raised yours, {user}.",
    "{user}, that opportunity died of old age waiting for you.",
    "You were in the room, {user}. That's not the same as being in the fight.",
    "{user}, the Senkaimon doesn't reopen for the undecided.",
    "Someone else read the reiatsu and you read it after, {user}.",
    "{user}, you arrived at the crime scene after the confession.",
    "That one's already been claimed — you're just browsing, {user}.",
    "Next time, {user}, move on instinct. Instinct beat you here.",
]

# Shown (publicly, mentioning the winner) when someone catches a spawn.
CONGRATS_QUOTES = [
    "Bankai-level instincts, {user}. Nicely caught.",
    "Sharp eyes, {user} - Soul Society would be proud.",
    "That catch had more precision than a Quincy's arrow, {user}.",
    "{user} moved like flash step itself. Well caught.",
    "Not even a Hollow could've snatched that one from you, {user}.",
    "Reiatsu well spent, {user}. That one's yours now.",
    "Captain-level reflexes right there, {user}.",
    "{user} caught it clean - Zangetsu would approve.",
    "{user} didn't hesitate. That's how it's done.",
    "Clean catch, {user} — no wasted movement.",
    "{user} read that one like a captain reads the battlefield.",
    "That was pure instinct, {user}. Well played.",
    "{user} snatched it before the dust settled. Impressive.",
    "Sharp as a Zanpakuto's edge, {user}.",
    "{user} got there first — that's all that matters.",
    "A flawless catch, {user}. Even Urahara would've smiled.",
    "{user} moved before anyone else even blinked.",
    "Textbook flash step, {user}. Textbook catch.",
    "{user} claimed it clean. No hesitation, no mercy.",
    "First to the draw, {user}. The rest can only watch.",
    "{user} named it like they'd known it all along.",
    "That's a Lieutenant's read and a Captain's timing, {user}.",
    "{user} caught it mid-stride. That's real instinct.",
    "No wasted reiatsu, {user}. Beautifully done.",
    "{user}, you read that signature like it was your own Zanpakuto.",
    "That was sharper than a Heilig Pfeil, {user}.",
    "{user} answered before the dust even rose.",
    "You felt it, you named it, you took it, {user}. Perfect.",
    "{user}, that's the kind of reflex they teach at the Academy — and rarely see.",
    "Quick hands, sharp mind, {user}. Well earned.",
    "{user} moved first and moved right. That's the whole game.",
    "That catch belonged to you the second it spawned, {user}.",
    "{user}, even Soi Fon would call that fast.",
    "Flawless read, {user}. No second-guessing, no delay.",
    "{user} took it like a captain takes a battlefield — instantly.",
    "That was a Hollow-hunting reflex, {user}.",
    "{user} caught it clean. The Gotei 13 would recruit you on the spot.",
    "No hesitation, no error — just a perfect catch, {user}.",
    "{user}, you were already moving before anyone else thought to.",
    "That one never stood a chance against you, {user}.",
]


def random_roast_quote(user_mention: str) -> str:
    return random.choice(ROAST_QUOTES).format(user=user_mention)


def random_congrats_quote(user_mention: str) -> str:
    return random.choice(CONGRATS_QUOTES).format(user=user_mention)